research_task:
  description: >
    Conduct a thorough research on latest AI tech like Agents, Huggingface in a way that
    learner can implement things right away in their companies.
  expected_output: >
    Generate an output/learning/tools.md with top 10 latest AI stuff/tools that brings most value to companies right now. Be thorough.
  agent: ai_master

learning_planning_task:
  description: >
    For each tool gather all required documentation and turn into tasks which can be turned into a interactive learning experience.
  expected_output: >
    - A file consisting of 100 tasks which you derive from the tools documentations. The file should cover most important aspects and focus more on
    practical skill acquisition. File put in output/learning/tasks.md
    - A file consisting of best method to really learn and understand the concepts, procedures and facts of the system. Output: output/learning/methods.md
    - A file consisting of both tasks.md and methods.md. They must be turned into a json file which will be used as a source for the web app. Note the task, method and
    how it should be represented in the app. Output: output/learning/source.json
  context: [research_task]
  agent: learning_expert

coding_task:
  description: >
    Create a stunning web app. Use data from learning_planning_task source.json as a source for content.
  expected_output: >
    React app that can be run locally. Use Tailwind and modern UI libraries for most effect.
    Write the app to output/learning/app folder.
    Make sure all the files are generated.
    Based on methods in the source.json, create best representation of it in UI, meaning, if task involves memorization and the method is flashcards, implement flashcards in the app.
    It must be a immersive learning experience where person can reflect later what they learned.
  agent: web_developer
  context: [learning_planning_task]

debugging_task:
  description: >
    Install dependencies for the app and do test runs to check if there are no errors.
  expected_output: >
    App dependencies can be installed.
    App runs without errors.
  agent: debugger
  context: [coding_task]
